[package]
name = "killswitch"
version = "1.0.1"
edition = "2024"

[dependencies]
axum = "0.7"
clap = { version = "4.5.49", features = ["derive"] }
kill_tree = "0.2.4"
tokio = { version = "1.38", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["fmt", "ansi"] }
